プルリクエストのテスト
masayatoida/MoneyCalcuator pull request #6
Opened 2021-05-13 22:20 UTC by masayatoida

プルリクエストのテストを作成しました。

2021-05-13 23:19 UTC, fuchi0741 commented
@masayatoida 素晴らしいですね！

次はビルドが通るように修正しましょう！

ブランチはそのままで修正を加えて、それ以降は
git add .
git commit -m "任意キーワード"
git push origin feature/test

これで上のCommitsが1 → 2に変更されます(新しくPRができるわけではないです)

2021-05-14 11:03 UTC, fuchi0741 reviewed
いい感じですね！

2021-05-14 11:04 UTC, fuchi0741 requested changes
ビルドできるようにしてください！

2021-05-14 11:36 UTC, masayatoida commented
このファイルがビルドできないから閉じます。

2021-05-14 11:36 UTC, closed without merging